# Generated by Django 3.2.6 on 2021-09-08 08:19

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
