# Generated by Django 3.2.6 on 2021-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
    ]
