# Generated by Django 3.2.6 on 2021-09-08 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options'),
        ('accounts', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_stars',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='posts_liked',
            field=models.ManyToManyField(blank=True, related_name='profiles_liked', to='blog.Post', verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
