# Generated by Django 3.2.6 on 2021-09-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210908_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts_liked',
        ),
    ]
