# Generated by Django 3.2.6 on 2021-09-16 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='link', max_length=50, verbose_name='link name')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'Relation', 'verbose_name_plural': 'Relations'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='relation',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=9, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True, verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='accounts.Link', verbose_name='links'),
        ),
    ]
