# Generated by Django 3.2.5 on 2021-10-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210916_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='state',
            field=models.CharField(choices=[('flw', 'followed'), ('blc', 'blocked'), ('req', 'requested'), ('acc', 'accepted')], max_length=3, null=True, verbose_name='state'),
        ),
    ]
