# Generated by Django 3.2.5 on 2021-10-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211003_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.profile', verbose_name='account'),
        ),
    ]
