# Generated by Django 3.2.6 on 2021-09-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210908_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='edited_at',
            new_name='date_edited',
        ),
    ]
