# Generated by Django 3.2.6 on 2021-09-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210908_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
