# Generated by Django 3.2.5 on 2021-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_like_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(choices=[(1, 'VERY_BAD'), (2, 'BAD'), (3, 'OK'), (4, 'GOOD'), (5, 'PERFECT')], null=True, verbose_name='star'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visits',
            field=models.ManyToManyField(blank=True, related_name='posts_visited', to='blog.IPAddress', verbose_name='views'),
        ),
    ]
