# Generated by Django 3.2.5 on 2021-11-13 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_auto_20211113_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('from a deleted user'), to='accounts.usermodel', verbose_name='user'),
            preserve_default=False,
        ),
    ]
