# Generated by Django 3.2.5 on 2021-11-24 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_relation_account'),
        ('blog', '0015_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('value', models.IntegerField(choices=[(1, 'VERY_BAD'), (2, 'BAD'), (3, 'OK'), (4, 'GOOD'), (5, 'PERFECT')], null=True, verbose_name='star')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('from a deleted user'), to='accounts.profile', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.profile', verbose_name='author'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='blog.post', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='vote',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_given', to='accounts.profile', verbose_name='profile voted'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('post', 'profile')},
        ),
    ]
